### PR TITLE
Fixes #250 Add mission and runtime in Projectile

### LINKED ISSUE #250: Add mission and runtime in Projectile
Mission and Runtime are set in the `UploadForm` class and it would be nice if they also existed in the Projectile, so this information could be used anywhere inside MissionControl

### PR DESCRIPTION
**Pull request by quintesse**
- [x] Have you created an [issue](https://github.com/openshiftio/launchpad-missioncontrol/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/openshiftio/launchpad-missioncontrol/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

### CODE REVIEW

**Comment by gastaldi** [comment]
Should we validate if mission/runtime are null?

**Comment by quintesse** [comment]
@gastaldi dunno, I just added the code in the same style as the rest (ie no null checking is being done). Also if we check for it we probably also need to handle the case they are null and have proper error handling. Not sure if that is within the scope of this issue?

**Comment by gastaldi** [comment]
Are these mission/runtime parameters always required? If so I think it makes sense to consider null checking in the build() method

**Comment by quintesse** [comment]
Well depends on what you mean by "required". Mission control will launch an app just fine if the information isn't present. There will just be less relevant statistics in Segment.
But like I said before: what do you do when the value is null? If what you want is just an assert and make the entire process fail if the fields are not available, sure we can do that.

**Comment by gastaldi** [comment]
It depends whether your Segment integration requires it. I'm fine with either approach

**Pull request merged**
