### PR TITLE
Add an updated nodejs jenkins slave.

### PR DESCRIPTION
**Pull request by lholmquist**
* Include node 8.1.4 and npm 5.3.0

- [] Have you created an [issue](https://github.com/openshiftio/launchpad-missioncontrol/issues) and used it in the commit message?
- [x] Have you checked to ensure there aren't other open [Pull Requests](https://github.com/openshiftio/launchpad-missioncontrol/pulls) for the same issue?
- [x] Have you built the project locally prior to submission with `mvn clean install`?

-----

This adds the nodejs jenkins slave that we forked and updated with the latest node and npm versions.  

This is part of a couple different commits to get the nodejs runtime integrated 

dev docs - https://github.com/openshiftio/appdev-documentation/pull/375
booster-catalog update - https://github.com/openshiftio/booster-catalog/pull/61

### CODE REVIEW

**Comment by lholmquist** [comment]
@gastaldi this should replace your PR #260

**Comment by gastaldi** [comment]
@lholmquist thanks. Can you confirm if declaring a new jenkins-slave will not consume much resources as supported in the openshift-free cluster?

**Comment by gastaldi** [comment]
This is needed for https://github.com/openshiftio/appdev-planning/issues/40

**Comment by lholmquist** [comment]
@gastaldi yea, i have no idea at this point :)    Let me see if i can get it running on my OSO free account

**Comment by Ladicek** [comment]
I'm no authority on this, but I think that:
- You declare an image stream, which itself costs virtually nothing. Ultimately, an image will be downloaded to the registry -- I'm not sure if this is counted against some kind of quota, but in this situation, it's the only thing that I know of that possibly could.
- The image stream has a special label which results in the Jenkins Kubernetes plugin noticing it and creating one more pod template. This again costs virtually nothing AFAIK.

**Comment by lholmquist** [comment]
@gastaldi @Ladicek i want to try and run this on my openshift online account.  How do i tell this template https://raw.githubusercontent.com/openshiftio/launchpad-templates/v6/openshift/launchpad-template.yaml to use my repo/branch for this PR for mission control.

I know how to change the location of the booster-catalog,  but i'm not sure how to change the location for the mission control repo

**Comment by gastaldi** [comment]
I believe `mvn fabric8:deploy` should upload your mission control binary to your minishift. Not 100% sure though

**Comment by lholmquist** [comment]
if that works for minishift,  then i'm assuming all i have to do to get it on OSO(not minishift) is the same thing, just log in with the `oc` differently

**Comment by lholmquist** [comment]
I tried doing that command with the backend first and it didn't seem to work.    There looked to be java null pointer execpetions in the logs,  of course though, i deleted that project on my minishift so i can see it now.


I also tried doing that with the mission control repo and got this mvn error:

```
~/develop/obsidian/openshiftio/launchpad-missioncontrol(nodejs-pipeline) » mvn clean fabric8:deploy                                                                                 lholmquist@lincolnhawk
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] missioncontrol-parent
[INFO] missioncontrol-base
[INFO] missioncontrol-service-github-api
[INFO] missioncontrol-service-openshift-api
[INFO] missioncontrol-core-api
[INFO] missioncontrol-service-github-impl
[INFO] missioncontrol-service-openshift-impl
[INFO] missioncontrol-core-impl
[INFO] missioncontrol-service-keycloak-api
[INFO] missioncontrol-service-keycloak-impl
[INFO] missioncontrol-web
[INFO] missioncontrol-tests
[WARNING] The POM for org.codehaus.mojo:sonar-maven-plugin:jar:5.1 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.codehaus.mojo:sonar-maven-plugin:5.1: Plugin org.codehaus.mojo:sonar-maven-plugin:5.1 or one of its dependencies could not be resolved: Failure to find org.codehaus.mojo:sonar-maven-plugin:jar:5.1 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
[WARNING] The POM for org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for org.eclipse.m2e:lifecycle-mapping:1.0.0: Plugin org.eclipse.m2e:lifecycle-mapping:1.0.0 or one of its dependencies could not be resolved: Failure to find org.eclipse.m2e:lifecycle-mapping:jar:1.0.0 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 30.2 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 19.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] missioncontrol-parent .............................. SKIPPED
[INFO] missioncontrol-base ................................ SKIPPED
[INFO] missioncontrol-service-github-api .................. SKIPPED
[INFO] missioncontrol-service-openshift-api ............... SKIPPED
[INFO] missioncontrol-core-api ............................ SKIPPED
[INFO] missioncontrol-service-github-impl ................. SKIPPED
[INFO] missioncontrol-service-openshift-impl .............. SKIPPED
[INFO] missioncontrol-core-impl ........................... SKIPPED
[INFO] missioncontrol-service-keycloak-api ................ SKIPPED
[INFO] missioncontrol-service-keycloak-impl ............... SKIPPED
[INFO] missioncontrol-web ................................. SKIPPED
[INFO] missioncontrol-tests ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.980 s
[INFO] Finished at: 2017-07-25T17:40:43+00:00
[INFO] Final Memory: 24M/383M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'fabric8' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/lholmquist/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
```

**Comment by gastaldi** [comment]
Ah I think I forgot the -Popenshift. So the command should be:

mvn fabric8:deploy -Popenshift

Em 25 de jul de 2017 14:45, "Lucas Holmquist" <notifications@github.com>
escreveu:

**Comment by lholmquist** [comment]
doesnt look like there is any "openshift" profile in the base of the project

**Comment by gastaldi** [comment]
You're right. That only exists in `launchpad-backend`. I haven't tested yet, but if we copy over the contents of the openshift profile in that project maybe that would help.

**Comment by lholmquist** [comment]
I figured out how to substitute my PR'd version of mission control into my running minishift,  but i haven't been able to get all the bits running on my free OSIO account, even using the slimmed down booster catalog branch.

while running this on minishift, it doesn't look like it takes up any more resources by just existing.   It just adds another image.  What else do we need to do to get this in?  Once this is in, then https://github.com/openshiftio/booster-catalog/pull/61 would be ready to make it in

**Comment by gastaldi** [comment]
Let's get this merged then and see what happens. If we find any trouble we can always revert :)

**Pull request merged**
